# Generated by Django 5.0.7 on 2024-08-05 08:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("airport", "0003_alter_order_user"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="ticket",
            options={"ordering": ["-order", "flight", "row", "seat"]},
        ),
    ]
