# Generated by Django 5.0.7 on 2024-08-06 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("airport", "0007_airplanetype_manufacturer"),
    ]

    operations = [
        migrations.CreateModel(
            name="AirplaneManufacturer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name="airplanetype",
            name="manufacturer",
        ),
        migrations.AlterField(
            model_name="airplanetype",
            name="name",
            field=models.CharField(max_length=255),
        ),
    ]
