# Generated by Django 5.0.7 on 2024-08-06 11:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("airport", "0008_airplanemanufacturer_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="airplanetype",
            options={"ordering": ["name", "manufacturer"]},
        ),
        migrations.AddField(
            model_name="airplanetype",
            name="manufacturer",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="airplane_types",
                to="airport.airplanemanufacturer",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="airplanetype",
            unique_together={("name", "manufacturer")},
        ),
    ]
